theme="ayu_dark"

[editor]
idle-timeout = 200

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
C-r = ":pipe-to kitty @ send-text --match recent:1 --stdin"
C-A-l = ":format"
C-A-s = ":sh echo -e %{filename}:%{linenumber} >> bookmarks.md"
C-A-c = ":sh echo -e %{filename}:%{linenumber} | xsel -b"
C-A-o = ":o %{selection}"
C-A-b = ":o bookmarks.md"

[keys.select]
C-r = ":pipe-to kitty @ send-text --match recent:1 --stdin"
C-A-s = ":sh echo -e %{filename}:%{linenumber} >> bookmarks.md"
C-A-o = ":o %{selection}"
C-A-b = ":o bookmarks.md"
