colorscheme gruvbox-dark
add-highlighter global/ number-lines
add-highlighter global/ show-matching
# add-highlighter global/ show-whitespaces
add-highlighter global/ wrap
set-option global tabstop 2
set-option global indentwidth 2

# add C highlighting to ino files
hook global BufCreate .*\.ino %{
    set-option buffer filetype c
}

# hook global WinCreate [^*]* %{
#         editorconfig-load
# }

hook global InsertChar . %{ try %{
        exec -draft hH <a-k>,\.<ret> d
            exec <esc>
}}

map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'

def ide %{
    rename-client main
    set global jumpclient main

    new rename-client tools
    set global toolsclient tools

    # new rename-client docs
    # set global docsclient docs
}

def send-repl %{
  execute-keys <a-|> 'kitty @ send-text --match recent:1 --stdin' <ret>
}

def send-ipython %{
  nop %sh{
    kitty @ send-text --match recent:1 '%cpaste\n'
  }
  send-repl
  nop %sh{
    kitty @ send-text --match recent:1 '\n--\n'
  }
}
# surround
def -params 2 surround %{
  execute-keys i %arg{1} <esc> a %arg{2} <esc>
}
declare-user-mode surround
map global surround p ':surround ( ) <ret>' -docstring '(Parenthesis)'
map global surround b ':surround [ ] <ret>' -docstring '[Brackets]'
map global surround c ':surround { } <ret>' -docstring '{Curly braces}'
map global surround \" ':surround \" \" <ret>' -docstring '"quotes"'
map global surround \' ":surround \' \' <ret>" -docstring "'apostrophes'"

map global user b ':terminal kak -c %val{session}<ret>' -docstring 'split buffer into new terminal'
map global user t ':terminal %sh{$SHELL}<ret>' -docstring 'open new terminal at current location'
map global user c ':comment-line<ret>' -docstring 'comment marked lines'
map global user e ':make-next-error<ret>' -docstring 'goto next make error'
map global user i ':ide<ret>' -docstring 'enter IDE mode'
map global user s ':enter-user-mode surround<ret>' -docstring 'surround mode'
map global user r ':send-repl<ret>' -docstring 'send to last window'
map global user p ':send-ipython<ret>' -docstring 'send to last window with ipython escape'

# binds
map global normal <F7> :make<ret>
map global normal <F6> :format<ret>
map global normal <a-s-c> %{<a-|>kitty +kitten clipboard<ret>}

# formatters
source "%val{config}/languages.kak"

# snippets + config
# TODO: init if not initialized
source "%val{config}/kakoune-snippets/snippets.kak"
source "%val{config}/kakoune-snippets/snippets-directory.kak"
map global insert <c-k> '<a-;>:snippets-select-next-placeholders<ret>'

