---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

keybinds:
    unbind: [Ctrl: 'p', Ctrl: 'n']

plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit

# Send a request for a simplified ui (without arrow fonts) to plugins
# Options:
#   - true
#   - false (Default)
#simplified_ui: true

# Choose the path to the default shell that zellij will use for opening new panes
# Default: $SHELL
# default_shell: fish

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
pane_frames: false

# Choose the theme that is specified in the themes section.
# Default: default
#theme: default

# Choose the mode that zellij uses when starting up.
# Default: normal
#default_mode: locked

# Toggle enabling the mouse mode.
# On certain configurations, or terminals this could
# potentially interfere with copying text.
# Options:
#   - true (default)
#   - false
#mouse_mode: false

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
#scroll_buffer_size: 10000

# Provide a command to execute when copying text. The text will be piped to
# the stdin of the program to perform the copy. This can be used with
# terminal emulators which do not support the OSC 52 ANSI control sequence
# that will be used by default if this option is not set.
# Examples:
copy_command: "xclip -selection clipboard" # x11
#copy_command: "wl-copy"                    # wayland
#copy_command: "pbcopy"                     # osx

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
# copy_clipboard: primary
