#!/bin/zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob nomatch

# keybinds
bindkey '^[[3~' delete-char

# vim binds
# bindkey -v

# emacs binds
bindkey -e
bindkey '^[[1;5D' emacs-backward-word
bindkey '^[[1;5C' emacs-forward-word

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/config/zsh/zshrc'

autoload -Uz compinit zmv
compinit
# End of lines added by compinstall

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

try_source () {
    [[ ! -f "$1" ]] || source "$1"
}
try_source ~/.config/zsh/functions.zwc
try_source ~/.config/zsh/aliases.zwc
try_source ~/.config/zsh/custom.zwc

# fzf bindings
try_source /usr/share/fzf/key-bindings.zsh
try_source /usr/share/fzf/completion.zsh
export FZF_DEFAULT_COMMAND='fd'
# bindkey "^R" history-incremental-search-backward

# add .local to path
export PATH="$HOME/.local/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"
