# git stuff
alias gf='git fetch'
alias gcl='git clone'
alias gco='git checkout'
alias gd='git diff'
alias ga='git add'
alias gst='git status'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'

#ls stuff
alias ll='ls -lF'
alias la='ls -laFA'
alias l='ls -CF'
alias dir='ls -laH'

#python stuff
alias pip='python -m pip'
alias pi='python -m pip install --user'
alias ipy='ipython3'

#misc stuff
alias here="nautilus . &"
alias dup='alacritty --working-directory "`pwd`"&'

#programming stuff
alias hl='highlight -O ansi'
alias ssh='ssh -A'
alias symsearch='nm -o --defined-only --demangle `find -name "**.so" -o -name "**.a" -o -name "**.o"` | fzf'
alias gdb='gdb-multiarch -q'
alias gdd='gdb-multiarch -q -x ~/.config/gdb/dashboard'
alias gef='gdb-multiarch -q -x ~/.config/gdb/gef.py'
alias r='R -q --no-save'
alias sizes="du --max-depth=1 -h"
alias texstack='docker run --rm -it --mount type=bind,src=$(pwd),dst=/workspace -u $(id -u):$(id -g) tex'
alias datasci='docker run -p 8888:8888 --rm -it  -e JUPYTER_ENABLE_LAB=yes -v $(pwd):/home/jovyan/work jupyter/datascience-notebook'

#clipboard
alias vim=nvim
alias uniconnect="sudo openconnect -u c7031199 vpn.uibk.ac.at"

alias fd=fdfind

# taskwarrior stuff
alias next="task next -BLOCKED"
alias backburner="task +backburner"
alias fin="task end:tod count"
alias todo="task sched:tod"
alias toda="task add sched:tod"
