#!/bin/bash

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f $XDG_CONFIG_HOME/bash/aliases ]; then
    . $XDG_CONFIG_HOME/bash/aliases
fi

if [ -f $XDG_CONFIG_HOME/bash/functions ]; then
  . $XDG_CONFIG_HOME/bash/functions
fi

# Base16 Shell
BASE16_SHELL="$XDG_CONFIG_HOME/base16-shell/"
if [[ ! -s "$BASE16_SHELL/profile_helper.sh" ]]; then
  echo "setting up base16-shell"
  git clone https://github.com/chriskempson/base16-shell.git $XDG_CONFIG_HOME/base16-shell
fi
[ -n "$PS1" ] && \
  [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
    eval "$("$BASE16_SHELL/profile_helper.sh")"

# configure rust if available
CARGO_ENV=$HOME/.cargo/env
if [[ -f $CARGO_ENV ]]
then
  source $CARGO_ENV
fi

LOCAL_PATH=$HOME/.local/bin
if [[ -d $LOCAL_PATH ]]
then
    export PATH=$PATH:$LOCAL_PATH
fi

export ENNCLAVE_HOME=~/Projects/eNNclave
export EDITOR=nvim
