#!/bin/bash

# search with preview of all matches using rp and fzf
rgs() {
  searchterm=$1

  result=`rg $searchterm --files-with-matches | fzf --preview "(highlight -O ansi 2>/dev/null {} || cat {}) | rg $searchterm --context 10 --pretty --colors 'match:bg:yellow'"`

  if ! [ -z $result ]; then
    vim $result +/$searchterm
  fi
}

# specialized preview for todos
td() {
result=`rg --vimgrep -i TODO | fzf --preview "echo {} | awk -F ':' -f ~/.awk/vimgrep_preview.awk"`
# result=`rg --vimgrep -i TODO | fzf --preview "echo {}"`

if ! [ -z $result ]; then
  IFS=':' read -ra PARTS <<< $result
  vim ${PARTS[0]} +${PARTS[1]}
fi
}

# tm, attach to tmux session for project
tm() {
    if [ -z "$1" ];
    then
        project=$(basename $(pwd))
    else
        project=$1
    fi

    tmux att -t "$project" || tmux new -s "$project"
}

# doc, start dev docker for current project
doc() {
    if [ -z "$1" ];
    then
        project=$(basename $(pwd))
    else
        project=$1
    fi

    docker exec -it "$project" bash 2>/dev/null || docker start -ai "$project"
}
